apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mimir-query-frontend
  namespace: monitoring
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/part-of: mimir-observability
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mimir-query-frontend
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: cortex_query_frontend_queries_in_flight
        target:
          type: AverageValue
          averageValue: "30"
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 300
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mimir-querier
  namespace: monitoring
  labels:
    app.kubernetes.io/component: querier
    app.kubernetes.io/part-of: mimir-observability
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mimir-querier
  minReplicas: 4
  maxReplicas: 12
  metrics:
    - type: Pods
      pods:
        metric:
          name: cortex_querier_queries_in_flight
        target:
          type: AverageValue
          averageValue: "20"
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
  behavior:
    scaleUp:
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
      stabilizationWindowSeconds: 60
    scaleDown:
      policies:
        - type: Percent
          value: 50
          periodSeconds: 300
      stabilizationWindowSeconds: 300
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mimir-store-gateway
  namespace: monitoring
  labels:
    app.kubernetes.io/component: store-gateway
    app.kubernetes.io/part-of: mimir-observability
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mimir-store-gateway
  minReplicas: 4
  maxReplicas: 12
  metrics:
    - type: Pods
      pods:
        metric:
          name: cortex_storegateway_queries
        target:
          type: AverageValue
          averageValue: "15"
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 300
