groups:
  - name: http_slo
    interval: 1m
    rules:
      - record: job:http_request:rate5m
        expr: sum by (job)(rate(http_requests_total{code!~"5.."}[5m]))
      - alert: SLOErrorBudgetBurn
        expr: |
          (
            sum(rate(http_requests_total{code=~"5.."}[5m])) /
            clamp_min(sum(rate(http_requests_total[5m])), 1)
          ) > 0.02
        for: 1h
        labels:
          severity: "page"
          team: platform
        annotations:
          summary: "SLO burn >2% over 1h"
          description: |
            Service {{ $labels.job }} is burning error budget faster than expected.
      - alert: SLOErrorBudgetBurn6h
        expr: |
          (
            sum(rate(http_requests_total{code=~"5.."}[30m])) /
            clamp_min(sum(rate(http_requests_total[30m])), 1)
          ) > 0.01
        for: 6h
        labels:
          severity: "warning"
          team: platform
        annotations:
          summary: "SLO burn >1% over 6h"
          description: |
            Service {{ $labels.job }} is consuming 1% error budget within 6h.
