groups:
  - name: http_slo
    interval: 1m
    rules:
      - alert: SLOErrorBudgetBurnFast
        expr: |
          job:http_request_error_ratio:5m{job!=""} > 0.14
          and
          job:http_request_error_ratio:1h{job!=""} > 0.02
        for: 5m
        labels:
          severity: "page"
          team: platform
        annotations:
          summary: "Fast burn-rate >14% over 5m and >2% over 1h"
          description: |
            Service {{ $labels.job }} is burning error budget rapidly. Escalate immediately.
      - alert: SLOErrorBudgetBurnMedium
        expr: |
          job:http_request_error_ratio:30m{job!=""} > 0.05
          and
          job:http_request_error_ratio:6h{job!=""} > 0.01
        for: 30m
        labels:
          severity: "warning"
          team: platform
        annotations:
          summary: "Moderate burn-rate >5% over 30m and >1% over 6h"
          description: |
            Service {{ $labels.job }} is consuming error budget faster than planned. Plan mitigation.
