apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cardinality-budgets
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: mimir-observability
    monitoring.grafana.com/shared-rules: "true"
    monitoring.grafana.com/rule-type: recording
spec:
  groups:
    - name: cardinality_budgets
      interval: 5m
      rules:
        - record: scrape_class:max_series_budget
          expr: scalar(800000)
          labels:
            scrape_class: "infra"
        - record: scrape_class:max_series_budget
          expr: scalar(400000)
          labels:
            scrape_class: "app"
        - record: scrape_class:max_series_budget
          expr: scalar(100000)
          labels:
            scrape_class: "noisy"
        - record: scrape_class:samples:sum
          expr: |
            sum(max_over_time(scrape_samples_post_metric_relabeling[5m])) by (scrape_class)
        - record: scrape_class:series_budget:ratio
          expr: |
            scrape_class:samples:sum
             / clamp_min(scrape_class:max_series_budget, 1)
        - alert: SeriesCardinalityBudgetExceeded
          expr: |
            scrape_class:series_budget:ratio > 0.8
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Cardinality budget over 80% for scrape class {{ $labels.scrape_class }}"
            description: "Review label usage for scrape class {{ $labels.scrape_class }}. Current ratio {{ $value | printf \"%.2f\" }}."
        - alert: SeriesCardinalityBudgetHardLimit
          expr: |
            scrape_class:series_budget:ratio > 0.95
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Cardinality budget exceeded for scrape class {{ $labels.scrape_class }}"
            description: "Drop noisy metrics or tighten relabeling for scrape class {{ $labels.scrape_class }}."
