fullnameOverride: mimir-index-cache
architecture: high-availability
replicaCount: 4
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9150"
  prometheus.io/path: "/metrics"
args:
  - "--conn-limit=8192"
  - "--max-item-size=5m"
  - "--verbosity=vv"
resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 2
    memory: 8Gi
podDisruptionBudget:
  enabled: true
  minAvailable: 3
persistence:
  enabled: false
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    selector:
      matchLabels:
        monitoring.grafana.com/class: infra
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: memcached
        app.kubernetes.io/instance: mimir-index-cache
networkPolicy:
  enabled: true
  allowExternal: false
