apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: mimir-observability
    monitoring.grafana.com/class: app
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  endpoints:
    - port: monitoring
      interval: 30s
      scrapeTimeout: 10s
      scheme: https
      tlsConfig:
        ca:
          secret:
            name: monitoring-ca
            key: ca.crt
        cert:
          secret:
            name: prometheus-mtls
            key: tls.crt
        keySecret:
          name: prometheus-mtls
          key: tls.key
